-- MySQL Script generated by MySQL Workbench
-- 03/24/17 02:28:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sekretariat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sekretariat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sekretariat` DEFAULT CHARACTER SET utf8 ;
USE `sekretariat` ;

-- -----------------------------------------------------
-- Table `sekretariat`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`school` (
  `idschool` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `patron` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postalcode` VARCHAR(6) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NULL,
  `isActive` INT NOT NULL,
  `info` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idschool`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postalcode` VARCHAR(6) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `pesel` VARCHAR(11) NOT NULL,
  `isActive` VARCHAR(45) NOT NULL,
  `salary` FLOAT NOT NULL,
  `info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idemployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`schoolclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`schoolclass` (
  `idschoolclass` INT NOT NULL AUTO_INCREMENT,
  `idschool` INT NOT NULL,
  `startYear` INT NOT NULL,
  `number` INT NOT NULL,
  `letter` VARCHAR(5) NULL,
  PRIMARY KEY (`idschoolclass`),
  INDEX `fk_schoolclass_school1_idx` (`idschool` ASC),
  CONSTRAINT `fk_schoolclass_school1`
    FOREIGN KEY (`idschool`)
    REFERENCES `sekretariat`.`school` (`idschool`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`teacher` (
  `idteacher` INT NOT NULL AUTO_INCREMENT,
  `isActive` INT NOT NULL,
  `idemployee` INT NOT NULL,
  `idschoolclass` INT NOT NULL,
  PRIMARY KEY (`idteacher`),
  INDEX `fk_teacher_employee1_idx` (`idemployee` ASC),
  INDEX `fk_teacher_schoolclass1_idx` (`idschoolclass` ASC),
  CONSTRAINT `fk_teacher_employee1`
    FOREIGN KEY (`idemployee`)
    REFERENCES `sekretariat`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_schoolclass1`
    FOREIGN KEY (`idschoolclass`)
    REFERENCES `sekretariat`.`schoolclass` (`idschoolclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`student` (
  `idstudent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postalcode` VARCHAR(6) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `pesel` VARCHAR(45) NOT NULL,
  `birthplace` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `beginDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `isActive` INT NULL,
  `indivinfo` VARCHAR(255) NULL,
  `achivinfo` VARCHAR(255) NULL,
  `idschoolclass` INT NOT NULL,
  PRIMARY KEY (`idstudent`),
  INDEX `fk_student_schoolclass1_idx` (`idschoolclass` ASC),
  CONSTRAINT `fk_student_schoolclass1`
    FOREIGN KEY (`idschoolclass`)
    REFERENCES `sekretariat`.`schoolclass` (`idschoolclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`subject` (
  `idsubject` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `obligatory` INT NOT NULL,
  PRIMARY KEY (`idsubject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`grade` (
  `idgrade` INT NOT NULL,
  `idstudent` INT NOT NULL,
  `idsubject` INT NOT NULL,
  `grade` FLOAT NOT NULL,
  PRIMARY KEY (`idgrade`),
  INDEX `fk_grade_student1_idx` (`idstudent` ASC),
  INDEX `fk_grade_subject1_idx` (`idsubject` ASC),
  CONSTRAINT `fk_grade_student1`
    FOREIGN KEY (`idstudent`)
    REFERENCES `sekretariat`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grade_subject1`
    FOREIGN KEY (`idsubject`)
    REFERENCES `sekretariat`.`subject` (`idsubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`studentparent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`studentparent` (
  `idstudentparent` INT NOT NULL AUTO_INCREMENT,
  `parentName` VARCHAR(45) NOT NULL,
  `parentSurname` VARCHAR(45) NOT NULL,
  `parentAddress` VARCHAR(45) NOT NULL,
  `parentPhone` VARCHAR(45) NOT NULL,
  `parentEmail` VARCHAR(45) NULL,
  `idstudent` INT NOT NULL,
  PRIMARY KEY (`idstudentparent`),
  INDEX `fk_studentparent_student1_idx` (`idstudent` ASC),
  CONSTRAINT `fk_studentparent_student1`
    FOREIGN KEY (`idstudent`)
    REFERENCES `sekretariat`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`fos_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`fos_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `username_canonical` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `email_canonical` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `salt` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `last_login` DATETIME NULL,
  `locked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL,
  `confirmation_token` VARCHAR(180) CHARACTER SET 'utf8' NULL,
  `password_requested_at` DATETIME NULL,
  `roles` LONGTEXT NOT NULL COMMENT '(DC2Type:array)',
  `credentials_expire_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekretariat`.`fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekretariat`.`fee` (
  `idfee` INT NOT NULL,
  `feename` VARCHAR(45) NOT NULL,
  `feevalue` FLOAT NOT NULL,
  `idstudent` INT NOT NULL,
  PRIMARY KEY (`idfee`),
  INDEX `fk_fee_idstudent_idx` (`idstudent` ASC),
  CONSTRAINT `fk_fee_idstudent`
    FOREIGN KEY (`idstudent`)
    REFERENCES `sekretariat`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
